# My Pipeline

trigger:
  branches:
    include:
      - main
      - feature/*

variables:
  Myvar: 'Sumit_Serv_Conn'
  MyWorkingDir: '$(System.DefaultWorkingDirectory)/Environment/Dev'
  MysusbID: '6e65d60a-bc12-4f70-8dcd-6cdb4da48e3e'

pr:
  branches:
    include:
      - main

stages:
  - stage: A
    displayName: Terraform_Init_Validate_Fmt_Plan
    pool: MyAgentPool
    jobs:
      - job: 
        steps:
        - task: TerraformTask@5
          displayName: Terraform_Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: $(MyWorkingDir)
            backendServiceArm: $(Myvar)
            backendAzureRmOverrideSubscriptionID: $(MysusbID)
            backendAzureRmResourceGroupName: 'sumuttestrg'
            backendAzureRmStorageAccountName: 'mycooolstorage'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'terraform.tfsate'

        - task: TerraformTask@5
          displayName: Terraform_Validate
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: $(MyWorkingDir)

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'custom'
            workingDirectory: $(MyWorkingDir)
            outputTo: 'console'
            customCommand: 'fmt'
            environmentServiceNameAzureRM: $(Myvar)
            environmentAzureRmOverrideSubscriptionID: $(MysusbID)

        - task: TerraformTask@5
          displayName: Terraform_Plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: $(MyWorkingDir)
            environmentServiceNameAzureRM: $(Myvar)
            environmentAzureRmOverrideSubscriptionID: $(MysusbID)


  - stage: B
    displayName: Scanning
    dependsOn: A
    pool: MyAgentPool
    jobs:
      - job: 
        displayName: tfsecanning
        steps:
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
            dir: $(MyWorkingDir)

  - stage: C
    displayName: Manual_Validation
    dependsOn: B
    pool: server
    jobs:
      - job:
        displayName: Manual_Validate
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'sumitvats08@omkarsingh88422gmail.onmicrosoft.com'
            approvers: 'sumitvats08@omkarsingh88422gmail.onmicrosoft.com'

  - stage: D
    displayName: Terraform_Apply
    dependsOn: C
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    pool: MyAgentPool
    jobs:
      - job:
        displayName: Terraform_Init
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: $(MyWorkingDir)
            backendServiceArm: $(Myvar)
            backendAzureRmOverrideSubscriptionID: $(MysusbID)
            backendAzureRmResourceGroupName: 'sumuttestrg'
            backendAzureRmStorageAccountName: 'mycooolstorage'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'terraform.tfsate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: $(MyWorkingDir)
            commandOptions: '--auto-approve'
            environmentServiceNameAzureRM: $(Myvar)
            environmentAzureRmOverrideSubscriptionID: $(MysusbID)

        
        

