# My Pipeline

trigger:  none

stages:
  - stage: A
    displayName: Terraform_Init_Validate_Fmt_Plan
    pool: My_Agent_Pool
    jobs:
      - job: 
        steps:
        - task: TerraformTask@5
          displayName: Terraform_Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
            backendServiceArm: 'Sumit_Serv_Conn'
            backendAzureRmOverrideSubscriptionID: '6e65d60a-bc12-4f70-8dcd-6cdb4da48e3e'
            backendAzureRmResourceGroupName: 'sumuttestrg'
            backendAzureRmStorageAccountName: 'mycooolstorage'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'terraform.tfsate'

        - task: TerraformTask@5
          displayName: Terraform_Validate
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'custom'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
            outputTo: 'console'
            customCommand: 'fmt'
            environmentServiceNameAzureRM: 'Sumit_Serv_Conn'
            environmentAzureRmOverrideSubscriptionID: '6e65d60a-bc12-4f70-8dcd-6cdb4da48e3e'

        - task: TerraformTask@5
          displayName: Terraform_Plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
            environmentServiceNameAzureRM: 'Sumit_Serv_Conn'
            environmentAzureRmOverrideSubscriptionID: '6e65d60a-bc12-4f70-8dcd-6cdb4da48e3e'


  - stage: B
    displayName: Scanning
    jobs:
      - job: 
        displayName: tfsecanning
        steps:
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
            dir: '$(System.DefaultWorkingDirectory)/Environment/Dev'

  - stage: C
    displayName: Manual_Validation
    jobs:
      - job:
        displayName: Manual_Validate
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'sumitvats08@omkarsingh88422gmail.onmicrosoft.com'
            approvers: 'sumitvats08@omkarsingh88422gmail.onmicrosoft.com'

  - stage: D
    displayName: Terraform_Apply
    jobs:
      - job:
        displayName: Terraform_Init
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
            backendServiceArm: 'Sumit_Serv_Conn'
            backendAzureRmOverrideSubscriptionID: '6e65d60a-bc12-4f70-8dcd-6cdb4da48e3e'
            backendAzureRmResourceGroupName: 'sumuttestrg'
            backendAzureRmStorageAccountName: 'mycooolstorage'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'terraform.tfsate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
            commandOptions: '--auto-approve'
            environmentServiceNameAzureRM: 'Sumit_Serv_Conn'
            environmentAzureRmOverrideSubscriptionID: '6e65d60a-bc12-4f70-8dcd-6cdb4da48e3e'

        
        

