# My Pipeline

trigger:  none

stages:
  - stage: A
    displayName: Terraform_Init_Validate_Fmt_Plan
    pool: My_Agent_Pool
    jobs:
      - job: 
        displayName: Terraform_Init
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
            backendServiceArm: 'Sumit_Serv_Conn'
            backendAzureRmOverrideSubscriptionID: '6e65d60a-bc12-4f70-8dcd-6cdb4da48e3e'
            backendAzureRmResourceGroupName: 'sumuttestrg'
            backendAzureRmStorageAccountName: 'mycooolstorage'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'terraform.tfsate'

        
        job: 

